# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            Sane Startup
tagline:          'End the Insanity'
description:      'Startup culture has lost its sensiblity, run sane startups today!'
url:              https://sane-startup.com
baseurl:          /

author:
  name:           'Anthony Metzler'
  url:            https://ametzler.com

paginate:         5

# Custom vars
version:          1.1.0
plugins:          [jekyll-paginate]
github:
  repo:           https://github.com/anthonymetzler/sane-startup
  user:           https://github.com/anthonymetzler

facebook-page:    https://www.facebook.com/sanestartup/
linkedin:         https://www.linkedin.com/in/anthonymetzler/
