# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sane Startups
tagline:          'Run sane startups today'
description:      'Startup culture has lost a lot of sensiblity, end the insanity now, and run sane startups today!'
url:              https://sane-startup.com
baseurl:          /

author:
  name:           'Anthony Metzler'
  url:            https://ametzler.com

paginate:         5

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/anthonymetzler/sane-startup
